echo "==> Stopping loging services"
/sbin/service rsyslog stop
/sbin/service auditd stop

echo "==> Removing old kernels"
/bin/package-cleanup --oldkernels --count=1 || true

echo "==> Cleaning up dhcp leases"
if [ -d /var/lib/dhcp ]; then
  /bin/rm -f /var/lib/dhcp/* || true
else
  /bin/rm -f /var/lib/dhclient/* || true
fi

echo "==> cleaning up udev rules"
/bin/rm -f /etc/udev/rules.d/70-* || true
/bin/rm -rf /dev/.udev/ || true
/bin/rm -f /lib/udev/rules.d/75-persistent-net-generator.rules || true

if [ -f /etc/salt/minion_id ]; then
    echo "==> Cleaning up minion_id for salt"
    /bin/rm -f /etc/salt/minion_id || true
fi

echo "==> Cleaning up SSH Keys"
/bin/rm -f /etc/ssh/*key* || true

echo "==> Cleaning wtmp and logs that we want to keep placeholders for"
/bin/cat /dev/null > /var/log/audit/audit.log 2>/dev/null || true
/bin/cat /dev/null > /var/log/wtmp 2>/dev/null || true
/bin/cat /dev/null > /var/log/lastlog 2>/dev/null || true
/bin/cat /dev/null > /var/log/grubby 2>/dev/null || true
/bin/cat /dev/null > /var/log/btmp 2>/dev/null || true
/bin/cat /dev/null > /var/log/messages 2>/dev/null || true

echo "==> Remove MAC address and UUIDs"
PRIMARY_INTERFACE=$(ip route list match 0.0.0.0 | awk 'NR==1 {print $5}')
/bin/sed -i '/^\(HWADDR\|UUID\)=/d' /etc/sysconfig/network-scripts/ifcfg-$PRIMARY_INTERFACE

echo "==> Clean out yum"
/usr/bin/yum clean all

echo "== Remove yum UUID"
/bin/rm -f /var/lib/yum/uuid

echo "==> Remove YUM cache"
find /var/cache/yum/ -type f -exec rm -f {} \;

echo "==> Removing caches"
find /var/cache -type f -exec rm -rf {} \;

echo "==> Cleaning up tmp"
/bin/rm -f /var/run/utmp
/bin/rm -rf /tmp/*
/bin/rm -rf /var/tmp/*

echo "==> Remove PAM data"
/bin/rm -rf /var/run/console/*
/bin/rm -rf /var/run/faillock/*
/bin/rm -rf /var/run/sepermit/*

echo "==> Remove process accounting log files"
if [ -d /var/log/account ]; then
    /bin/rm -f /var/log/account/pacct*
    touch /var/log/account/pacct
fi

echo "==> Remove any crash data generated by ABRT"
/bin/rm -rf /var/spool/abrt/*

echo "==> Clean out  user's home"
/bin/rm -rf /home/*/.ssh/*
/bin/rm -rf /root/.ssh/
/bin/rm -f /root/anaconda-ks.cfg
/bin/rm -f /root/*log*

echo "==> Remove local machine ID"
if [ -d /etc/machine-id ]; then
    /bin/rm -f /etc/machine-id
    touch /etc/machine-id
fi
if [ -d /var/lib/dbus/machine-id ]; then
    /bin/rm -f /var/lib/dbus/machine-id
    touch /var/lib/dbus/machine-id
fi

echo "==> Cleaning up log files"
/usr/sbin/logrotate -f /etc/logrotate.conf 2>/dev/null || true
/bin/rm -f /var/log/*-* /var/log/*.gz 2>/dev/null || true
/bin/rm -f /var/log/dmesg.old
/bin/rm -rf /var/log/anaconda
/usr/bin/find /var/log -type f | while read f; do echo -ne '' > "$f"; done;

echo "==> Remove email from local mail spool"
/bin/rm -rf /var/spool/mail/*
/bin/rm -rf /var/mail/*

echo "==> Clear user history"
history -c || true
unset HISTFILE || true
